version: '3.8'

services:
  backend_service:
    build: .
    # Name of the container for easier identification
    container_name: backend_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # We define a local network for this project
    networks:
      - app_network
    # Consistent with the EXPOSE port in your Dockerfile
    command: python manage.py runserver 0.0.0.0:8000

networks:
  app_network:
    driver: bridge